#!/usr/bin/env python3
"""Train DNN (Keras) for ARP attack detection based on arp_dataset.csv.

Input: CSV generated by collector.py
Output:
  - models/arp_attack_detection_model.h5
  - models/arp_dnn_preprocess.joblib (StandardScaler + feature list)
Optional:
  - results/dnn_history.csv and figs/dnn_training.png (loss/accuracy curves)

This script keeps the feature set consistent with the runtime firewall (arp_firewall_dnn.py).
"""
import argparse
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

DEFAULT_FEATURES = [
    "opcode", "src_ip_oct", "dst_ip_oct",
    "src_mac_b", "dst_mac_b",
    "is_request", "is_reply",
    "is_gratuitous", "dst_mac_zero",
    "req_rate_1s", "mac_change_count"
]

def label_to_int(v: str) -> int:
    v = str(v).strip().lower()
    return 1 if "attack" in v else 0

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data/arp_dataset.csv", help="Merged dataset CSV")
    ap.add_argument("--model_out", default="models/arp_attack_detection_model.h5")
    ap.add_argument("--prep_out", default="models/arp_dnn_preprocess.joblib")
    ap.add_argument("--history_out", default="results/dnn_history.csv")
    ap.add_argument("--plot_out", default="figs/dnn_training.png")
    ap.add_argument("--no_plot", action="store_true")
    args = ap.parse_args()

    df = pd.read_csv(args.data)

    missing = [f for f in DEFAULT_FEATURES if f not in df.columns]
    if missing:
        raise SystemExit(f"Missing columns in dataset: {missing}")
    if "label" not in df.columns:
        raise SystemExit("Dataset must have column 'label' from collector.py")

    X = df[DEFAULT_FEATURES].astype(float).values
    y = df["label"].apply(label_to_int).values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    # Dense-stack (DNN) – close to the paper style
    model = Sequential([
        Dense(64, activation="relu", input_shape=(X_train_s.shape[1],)),
        Dropout(0.1),
        Dense(32, activation="relu"),
        Dense(16, activation="relu"),
        Dense(8, activation="relu"),
        Dense(4, activation="relu"),
        Dense(2, activation="relu"),
        Dense(1, activation="sigmoid"),
    ])
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

    early = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

    hist = model.fit(
        X_train_s, y_train,
        epochs=50, batch_size=32,
        validation_split=0.2,
        callbacks=[early],
        verbose=1
    )

    loss, acc = model.evaluate(X_test_s, y_test, verbose=0)
    print(f"[EVAL] loss={loss:.6f} acc={acc:.4f}")

    # save model + preprocess
    model.save(args.model_out)
    joblib.dump({"scaler": scaler, "features": DEFAULT_FEATURES}, args.prep_out)
    print(f"[OK] Saved model: {args.model_out}")
    print(f"[OK] Saved preprocess: {args.prep_out}")

    # save history
    hist_df = pd.DataFrame(hist.history)
    hist_df.to_csv(args.history_out, index=False)
    print(f"[OK] Saved training history: {args.history_out}")

    if not args.no_plot:
        import matplotlib.pyplot as plt
        from pathlib import Path
        Path(args.plot_out).parent.mkdir(parents=True, exist_ok=True)

        plt.figure()
        if "loss" in hist_df:
            plt.plot(hist_df["loss"], label="loss")
        if "val_loss" in hist_df:
            plt.plot(hist_df["val_loss"], label="val_loss")
        plt.title("DNN training/validation loss")
        plt.xlabel("epoch")
        plt.ylabel("loss")
        plt.legend()
        plt.tight_layout()
        plt.savefig(args.plot_out, dpi=200)
        print(f"[OK] Saved plot: {args.plot_out}")

if __name__ == "__main__":
    main()
